export const createdMockExcuse = {
    id: "",
    title: "A mock excuse",
    dateCreated: new Date().toISOString().slice(0, 10),
    content: "This is a mock excuse generated by submitting the form."
};